### ISSUE TITLE
Add wildcard for service name

### ISSUE THREAD

**Issue by maxired** [prdn/pigato#11]
Hi,

The current implementation of the broker doesn't allow to use a wildcard mechanism to route query.
I think this would be a great improvement.

I am trying to serve a website with pigato, and want different workers to deal with dynamic queries or static files without configuration except on the worker.

I wish my worker dealing with static files to be started with 
```javascript

var worker = new Worker('tcp://' + conf.broker.host + ':' + conf.broker.port, 'http/mywebsite.com/*')

```
whereas dynamic URI to be declared with the full uri , such as
```javascript
var worker = new Worker('tcp://' + conf.broker.host + ':' + conf.broker.port, 'http/mywebsite.com/stock')
```
Would you be open for a contribution in this direction ?

**Comment by prdn** [comment]
Hi,

I'm doing the same thing with express.

```
var _ = require('lodash');
var PIGATO = require('pigato');

var app = express();
var fcc = new PIGATO.Client('tcp://localhost:55555');

app.enable('jsonp callback');
http.createServer(app)
  .listen(8080);
  return true;
});

app.use(compress());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json())

function controller(req, res) {
 var query = _.extend({}, req.query, req.body);

  var route = {
    service: query.service
  };

 fcc.request(
    'NS-' + route.service.toUpperCase(), 
    data, undefined,
    function(err, out) {
      res.end(out, 'UTF-8');
    }, 
    { timeout: -1 }
  );
}

app.get('/api/:service/:controller/:action', controller);
app.post('/api/:service/:controller/:action', controller);
```

So your workers can offer services such as ```NS-stock``` , ```NS-otherservice```

Let me know if this helps.

**Comment by maxired** [comment]
Hi, 
thanks for your answer.

Since, you mention Express, I will use it to explain in a better way what I mean  : 
I wish something similar to express routing but with the service name, and this routing to be done in the broker.

Your sample implementation works well because your services have the same granularity, but is not very flexible.

**Comment by prdn** [comment]
Hey @maxired 

I've published the wildcard support based on your suggestions.
It has been a bit more difficult than I thought but now it seems to work well.

**Comment by maxired** [comment]
Hey @prdn , thanks for hard work.

From what I see, I am not sure that every feature from #13 are there, are you aware of this ? 
I am thinking for example of the priority for multiples services with wildcards.

More globally, Is there any reason why you didn't merged the PR ?

**Comment by prdn** [comment]
The reason why I haven't merged your request is that I had to make a lot changes to the current code to let the wildcards working correctly in all the scenarios (wildcard worker arrives before client, viceversa, ...). In the meantime I fixed a couple of bugs.

I hope this is not a problem for you and I really appreciate your help to improve the mechanism adding the priority.
