### ISSUE TITLE
Multiples services in a Worker

### ISSUE THREAD

**Issue by maxired** [prdn/pigato#12]
Hi,

Currently, a Worker can deal with only one service.
I wish a node could easily provide several services, without the overhead of having multiples Workers ( impact in terms of memory, open files (new socket) ... ) 

Would you be open for a contribution implementing this ?

**Comment by prdn** [comment]
Hi,

I think creating multiple instances of a worker should not impact so much on your memory, but consumes more sockets.
By pattern a worker should offer a single service for various reasons:
- it's easier to keep track when a worker is available for a given service
- so the broker has a very tiny and fast map between services names and workers
- the overall structure is easier and more bug free

I have to think a little more about this change, we may think to something hybrid for the wildcards...

**Comment by maxired** [comment]
Hi,

I agree with you to say that this is probably not a top priority evolution for the project.
Still, I might try later to implement this.

**Comment by bmeck** [comment]
I would avoid having multiple services per worker. That would mean workers have multiple purposes. Adding a router so that multiple workers can take up 1 socket might be a better alternative.

**Comment by prdn** [comment]
Close this for now.
