### ISSUE TITLE
No parallels query for a worker ?

### ISSUE THREAD

**Issue by maxired** [prdn/pigato#14]
Hi,

from what I understand from the code, if we want to send multiples queries to a worker, the queries will be done one after the other ? I am correct ?  I understand this from the call  to [serviceWorkerUnwait](https://github.com/prdn/pigato/blob/f3c1ba191ae3af422efa205df4cf682a43058f7e/lib/Broker.js#L472), and also the use of self.lock which seems even more restrictive ( One request by service ? ) 

If so, is there any good reason to justify that ? This seems to me to be counter intuitive, specially when using Node.JS.

**Comment by maxired** [comment]
worker.rid seems also to be a problem to address.

**Comment by prdn** [comment]
I think you're right. 
The lock is a mess and I'm going to fix it.

Fixed the lock you should be able to send concurrent requests for a single service because dispatch is called every time a message arrives.

**Comment by prdn** [comment]
the worker.rid is fine
A worker can handle 1 request per time.

**Comment by maxired** [comment]
>the worker.rid is fine
>A worker can handle 1 request per time

Why is that ?
The unit test I made seems to prove otherwise

**Comment by bmeck** [comment]
@prdn is there any problem making a worker type that handles multiple requests at a time? Right now we are using both dealer and router sockets so multiple requests can theoretically be handles like http://zguide.zeromq.org/java:mtserver

**Comment by maxired** [comment]
From what i understand, the lock is already useless, since the call to
```javascript
 handle(workerId, worker, done);
``` 
will call 'done' after the message is send, but not after the response is received.

As say just before, i thinks worker already can handle multiple requests at a time

**Comment by prdn** [comment]
@maxired It seems that in your test you're using only 1 worker.
If you have 3 workers and 100 requests the 3 workers work in parallel (the lock is messed so I'm going to fix it).

However we have to choose if a worker should or shouldn't handle multiple requests in parallel.
Handling more requests in parallel sure we can better use the I/O time to serve other requests.

Let think about any issue and if no one can't find it let's do it.

@maxired yes I'm going to remove it.

**Comment by prdn** [comment]
ps in the meantime the lock has gone

**Comment by bmeck** [comment]
If we do handle things in parallel a max queued messages would be good so
you can limit the number of pending queries (I think this is more an edge
case though).

**Comment by prdn** [comment]
I think that each worker should tell how many requests it is able to handle at the same time

**Comment by bmeck** [comment]
As long as Infinity is an option that seems fine.

**Comment by prdn** [comment]
Yes sure.
A worker may vary that value depending on its load

**Comment by maxired** [comment]
This could be a good feature. 
I am not sure of your usage of this library, but in my case, a default option with unlimited seems good to me.

**Comment by bmeck** [comment]
@maxired we currently have limits to prevent memory usage from peaking, but I think we are a in the minority

**Comment by prdn** [comment]
Ok let's design a little bit this thing.
I probably want to design a possible implementation during the weekend.
There will be a major design of Worker and some changes to the Broker

**Comment by maxired** [comment]
I'll also try an implementation on top of my current changes.
@prdn , why do you think there is lot of work on the Worker ?

**Comment by prdn** [comment]
@maxired because the Worker is very small now and adding that feature should change its overall structure. Nothing hard however

**Comment by prdn** [comment]
I've committed a first version of the parallel workers. Now they can receive up to 100 concurrent requests but I'm going to add an infinite default limit and the possibility to configure that limit.

**Comment by prdn** [comment]
ps. there are few other changes.
now we use node-uuid instead of shortid and moved to zmq-2.10.0 and readable-stream 1.1.13.

**Comment by maxired** [comment]
Hi,
Do you have any plan to add/integre units test for this part. The one from https://github.com/prdn/pigato/pull/15 might sill be a good start.

**Comment by prdn** [comment]
Do you mean this one?
https://github.com/maxired/pigato/commit/d52b597b24bd83759e3b75df96612cd04e9f844a

**Comment by maxired** [comment]
@prdn , I was more thinking about the one from https://github.com/maxired/pigato/commit/d6c59b1ea230fa423693c5b2e37b799003f9c53c , if you remove the wildcard  part

**Comment by prdn** [comment]
Ok, I'm going to add it. 
Thank you :-)

**Comment by prdn** [comment]
Test integrated.
I've fixed a couple of bugs and we have also a concurrency configurable parameter that is delivered by worker heartbeats called "concurrency".
You can use -1 for infinite concurrency, default is 100

```
new PIGATO.worker(location, 'echo', { concurrency: -1 });
```

**Comment by maxired** [comment]
Awesome, i would have done it the same way

**Comment by prdn** [comment]
Thank you.
I added you in the collaborators list.

**Comment by prdn** [comment]
I'm going to update the npm version tomorrow
