### ISSUE TITLE
Client not closing

### ISSUE THREAD

**Issue by leonpegg** [prdn/pigato#17]
When calling stop on a client it does not actually close the zmq socket (file handle)

this causes the process to run out of file handles even if the client is no longer in use.

**Comment by prdn** [comment]
I've added a system test and released v0.0.33 version of Pigato.

This code below makes zeromq to run out of sockets
```
for (var ci = 0; ci < 10000; ci++) {
  var c = new PIGATO.Client(bhost);
  c.start();
  c.stop();
}
```

But in the test I've prepared `test/system.js` you'll see that it is sufficient to wait until the next event loop to let zmq to cleanup file descriptors.

**Comment by leonpegg** [comment]
This was exactly the problem, I should of included an example.

Thanks for this will update Pigato and check out the test.

**Comment by prdn** [comment]
I close this for the moment. Let me know if you have more issues
