### ISSUE TITLE
What does test "test/system.js" ?

### ISSUE THREAD

**Issue by maxired** [prdn/pigato#24]
Hi,

looking at *test/system.js*, I am not sure what this file is supposed to test. 
It looks like a performance test, but the fact that there is no *assert* is kind of weird.

Because the connection between a client and a worker is asynchronous, we don't really know what is done in the meantime.

**Comment by prdn** [comment]
Hi @maxired 

that was intended to consume file descriptors and see if pigato/0mq can free them correctly.
If you want you can change it in something more meaningful.

Thanks

**Comment by prdn** [comment]
Closing
