### ISSUE TITLE
Usefullness of timeout in tests ?

### ISSUE THREAD

**Issue by maxired** [prdn/pigato#25]
Hi,

I am currently trying to remove/shorten the timeouts in the unit tests.
Is there any reasons why you set them at high value ?

I sometimes have ZeroMQ (4.0.4+dfsg-2+deb.sury.org~precise+1) error like : 
- ``` zmq_assert (it != outpipes.end ());```
- ```Resource temporarily unavailable (signaler.cpp:236)```
- ```Assertion failed: ok (mailbox.cpp:82)```
- ```*** glibc detected *** node: double free or corruption (fasttop)Aborted```

**Comment by prdn** [comment]
Hi @maxired 

this below is a well known problem in ZeroMQ that has been resolved in 4.1.0. 
It is due to the fact that sometimes ZeroMQ fails to unbind a `inproc` socket.

```
....
Assertion failed: ok (mailbox.cpp:82)
....
```

Should we avoid using `inproc` for the moment?

**Comment by prdn** [comment]
If you want to remove timeouts you should also change the internal timeouts of Client/Worker/Broker for heartbeating and liveness check.

**Comment by maxired** [comment]
Hi @prdn ,

Looks like I have no more error using 4.1.0-rc1. 
Maybe we should just advice people to use it.

I am not sure whether my goal is to totally removed all timeouts, this seems to be really difficult because the way connections are handled by zeromq. 

What I though for just setting low heartbeat and timeouts for tests, and finally removing timeouts where it can be easily avoided .
I'll do a pull request and let you choosed ;)

**Comment by prdn** [comment]
Closing after merge. thank you :-)
