### ISSUE TITLE
Is it a typo?

### ISSUE THREAD

**Issue by wcp1231** [prdn/pigato#28]
https://github.com/prdn/pigato/blob/master/lib%2FBroker.js#L81

```js
_.each(self.services, function(service, srvName) {
  if (!service.workers.length) {
    supd = true;
    delete self.services;
  }
});
```

should `delete self.services` to be `delete self.services[srvName]` ?

**Comment by prdn** [comment]
You're right.
Fixed the issue.

Thank you very much
