### ISSUE TITLE
Broker can't be totally clean

### ISSUE THREAD

**Issue by maxired** [prdn/pigato#29]
Hi, when starting and closing a broker, node.js doesn't finish 
You can reproduce with the following sample : 
```javascript
var zmq = require('zmq');

var bhost= "inproc://#titit";

var PIGATO = require('./');
var broker = new PIGATO.Broker(bhost);
broker.start(
    function(){
    console.log("started");
    broker.stop( function(err){
      console.log("stopped", err);
      } );}, 200);
```

```
$node testBroker.js 
started
stopped undefined
```

This is because [here](https://github.com/prdn/pigato/blob/c73556de26351969acda88548130207e6b65ea18/lib/Broker.js#l69l88) in the start method, we create a setInterval, but don't save the intervalId, and don't delete it in the stop method.

**Comment by prdn** [comment]
Thanks @maxired
