### ISSUE TITLE
Hearbeat from client can be badly forwarded

### ISSUE THREAD

**Issue by maxired** [prdn/pigato#32]
Hi,

When I connect a client to 2 (or more) brokers, and each of the broker have a worker for a current service,
from a long request, when I call 'heartbeat(req.id)' on my client, the hearbeat is not always forwarded to the good worker.

I suspect it to be because of the way the dealer socket work in ZMQ, but haven't investigated more.

**Comment by maxired** [comment]
If I understand correctly, if we want to keep the abilty to have multiples brokers for a client, and be able to send hearbeat for a request ( sending to a specific broker which will forward to a specific worker),
the Client to Broker link should be Router-To-Router instead of Dealer-to-Broker.

What do you think ?

**Comment by prdn** [comment]
You're right.
We should refactor the multi-broker stuff on the Client.
The Client should handle multiple sockets, heartbeating for each Broker, etc...

I would maintain the Dealer socket type for the Client

**Comment by maxired** [comment]
You are right, Router-To-Router will not work in this case.
Do you think the multi broker stuff should be part of the library ?

My opinion is that it might not be mandatory, and that implementing a fully working solution will increase Client complexity a lot. A long term solution might be to have Broker to Broker communication possible. http://zguide.zeromq.org/page:all#Federation-Versus-Peering .This will keep Client and Worker simple, which is good if we want create Client and Worker in other languages.

In the mean time, I think that somebody with a multi broker need can instantiate severals clients. ( Just as we decided for a Worker providing multiples services).

What do you think ?

**Comment by leonpegg** [comment]
I was actually going to bring up the client connection to multiple brokers in regards to #18 as ZAP requires you to define a auth server and I was unable to work a solution with multiple brokers.

**Comment by prdn** [comment]
Yes, let's do that. 
Users can now instantiate multiple clients with different Broker.
Current multi-broker support is quite useless.
