### ISSUE TITLE
frontend facing webservices. Pigato good solution? 

### ISSUE THREAD

**Issue by gebrits** [prdn/pigato#33]
So, I'm more at home with message structures for the backend, e.g.: enriching documents based on CEP, CQRS type of stuff with Kafka etc. 

However, currently a client has asked to look into restructuring a large legacy code-base + new functional stuff on top into several webservices (8 for now). This stuff needs to be exposed through a Restful API to frontend clients. 

I picture the following flow/user story. Would really appreciate your input if thinking is correct and if Pigato (+zeroMQ) would be the way to go: 

- there's a API layer which acts as a proxy/facade for the entire system. 
- a client may request a resource by talking to the api -layer
- the api-layer has knowledge on how to compose a response for each particular request. 
- for that, it needs to (often in parallel, sometimes sequentially) get sub-responses from other parts of the system, and combine them together to form the response. 
- the API-layer doesn't want to know which services in the system do what. In fact it doesn't want to know which services exist at all. 
- Therefore it chooses to put it's messages on a message bus/queue. 1 message for each subresource it wants to receive
- Messages are passed using req/resp protocol (instead of pub/sub) because the API-layer (the requester) wants to know when all sub-responses are received so it can start it's task of composing the final response. 

This story may be typical for some, but it's pretty new to me. 
Would you say the above story is correct in how a message bus fit's in? 
Am I correct in not wanting pub/sub because I can't see how the api-layer (the requester) would know when it has received all responses? 

And lastly, would Pigato (+ zeroMQ) offer us a good solution / abstraction to approach this? 

P.s.: I'm looking into simple service buses, instead of brokers because part of the routing logic will end up in the routing-table of said brokers. This to me causes friction with wanting to have your microservices as loosely coupled as possible. Would you agree?

**Comment by prdn** [comment]
Hi,

Pigato is good in distributed RPC.
In my company I use pigato as RPC and message broker system to handle complex workflows in a distributed context.
We also offer REST APIs, so we started using pigato + expressjs.
The idea is very simple.

```
var app = express();
app.enable('jsonp callback');

var srv = http.createServer(app)
.listen(CONF.port);

app.use(compress());
app.use(bodyParser.urlencoded({ extended: true, limit: '20mb' }));
app.use(bodyParser.json({ limit: '20mb' }))

var fcc = new PIGATO.Client('tcp://' + CONF.broker.host + ':' + CONF.broker.port);

function controller(req, res) {
  var query = _.extend({}, req.query, req.body);
  var route = {
    service: query.service,
    controller: query.controller,
    action: query.action
  };

 fcc.request(
    'API-' + route.service + '-' + route.controller + '-' + route.action, 
    query, undefined,
    callback
  );
}

app.get('/api/:service/:controller/:action', controller);
app.post('/api/:service/:controller/:action', controller);
```

Then you can implement pigato services for everything that you want to offer with your REST APIs.

Remember also that you can create complex workflows with pigato.
A pigato worker can use pigato client to request data from other workers to perform elaborations.
You should avoid infinite dependency loops, but it work greatly :-)

Hope to have answered to your question.

**Comment by gebrits** [comment]
Cheers for confirming. 

For our relatively simple use-case (an API mixing-and-matching responses from various microservices) I'm hesitant to go the route of having microservices themselves push out messages and let them cooperate. I'd rather let my API-layer be a front-controller (to throw a pattern around) and control the whole bunch. This seems to bundle the routing-logic with one entity (the API layer) which is ultimately responsible for the response formatting/mapping anyway. 

I'm curious what you believe are advantages, in my particular situation, of having microservices cooperate with eachother, instead of being reasonably 'dumb' workers merely responding to message-requests. Thoughts?

**Comment by prdn** [comment]
I think that having microservices will only increase the scalability of your server side structure and let you to expand it very easily, compared to an usual router<->controller pattern. 
If your application will be constantly simple in his structure I agree with you that you may not need cooperating microservices

**Comment by gebrits** [comment]
Thanks @prdn. appreciated.
