### ISSUE TITLE
[Client onMsg] emitErr vs doing nothing is not coherent

### ISSUE THREAD

**Issue by maxired** [prdn/pigato#35]
Hi,

When handling messages on the client library, when handling unknown messages there are cases when we emit error, and case when we do nothing. This should probaly be uniformized.

Currently,
We emit error when : 
 - we received a message with a header different from MDP.CLIENT
 - we received a message of length >=3 and whose type is neither MDP.W_HEARTBEAT nor MDP.W_REPLY nor MDP.W_REPLY_PARTIAL

We don't emit error when : 
 - we received a message whose length is <3 and type different of MDP.W_HEARTBEAT
 - we received a message whose requestId is unknown

I am not sur this should really be considered as client side error; this is probably more usefull for debugs than anything. What do you think should be the good behavior ?

**Comment by prdn** [comment]
I'll add errors for that

**Comment by prdn** [comment]
Closed via d726bd4da42f1af034dbd3b8da79c0877b9623d3

**Comment by maxired** [comment]
Look better to me ;) thx
