### ISSUE TITLE
[Worker] hbtimer cleared asynchronously may lead to problems

### ISSUE THREAD

**Issue by maxired** [prdn/pigato#38]
Hi,

On the worker side,  when handling with a reconnection, after for example the `liveness` being 0, the hbtimer is [not cleared immediatly.](https://github.com/prdn/pigato/blob/f27ae674b080d801f87a6c816fdf80de2975cd02/lib/Worker.js#L81L83) but later, in the [stop](https://github.com/prdn/pigato/blob/f27ae674b080d801f87a6c816fdf80de2975cd02/lib/Worker.js#L99) method. 

This is indeed launched after the `conf.reconnect` ms.

When `conf.reconnect` is greater than `conf.heartbeat`, this lead to a bad behavior : [the function linked to hbtimer ](https://github.com/prdn/pigato/blob/f27ae674b080d801f87a6c816fdf80de2975cd02/lib/Worker.js#L76L92) will be called several times with the livenness being 0 or negative, and so the start method will later be called several times, sending more 'W_DISCONNECT' and 'W_READY' than necessary , and probably resulting in old `hbtimer` never been deleted.

I haven't checked, but this might also appeared with  `conf.reconnect` equal or lower than `conf.heartbeat` on a system with high load.

**Comment by prdn** [comment]
@maxired this should fix f789331e6eff8ebdfa3fd2e415c60cdf0523f49c

**Comment by maxired** [comment]
@prdn , I can confirm that the problem is solved.
Thanks for fast reaction.
I'll send you soon some more unit tests for the Worker, with one testing this case.
