### ISSUE TITLE
[Broker] No HEARTBEAT message sended to Worker

### ISSUE THREAD

**Issue by maxired** [prdn/pigato#43]
Hi,

I just figured out that the Broker currently doesn't send heartbeat message back to workers. (Except heartbeat for a specific request).

This lead to worker disconnecting and reconnecting endlessly.

**Comment by maxired** [comment]
My issue was du the heartbeat conf being different on the worker and on the broker.
I am not exactly sure what should be the behavior in this case.

When conf are the same, everything is working fine, because the Broker send message to the Worker, in the [workerChecks](https://github.com/prdn/pigato/blob/23713cbe6dc1190dd5ced2fa791e687626f00192/lib/Broker.js#L64L66) method 

If config are different then we don't send exactly one heartbeat for each hearbeat received. If the broker heartbeat conf is much more bigger than the worker heartbeat conf, then it lead to lots of reconnection.

**Comment by prdn** [comment]
Thanks @maxired
