### ISSUE TITLE
response.end() first argument required

### ISSUE THREAD

**Issue by DenisGorbachev** [prdn/pigato#50]
Currently, pigato requires the worker to call `response.end(something)`. If you just call `response.end()`, the W_REPLY will not be sent. That means you can't `fs.createReadStream("/some/file").pipe(response)` (despite what README states). That's because official Streams API states that last argument to `.end()` is optional, and `fs.createReadStream` indeed calls `.end()` without arguments.

Could you please fix it?

**Comment by prdn** [comment]
6ac1911e4dc233240962a456ec09f7b3abd6a8b8 should fix this one.
Let me know if it works for you.

Thanks

**Comment by prdn** [comment]
Seems correctly fixed

**Comment by DenisGorbachev** [comment]
oh, missed your first comment... thanks for the fix!
