### ISSUE TITLE
worker heartbeat not working

### ISSUE THREAD

**Issue by kubi** [prdn/pigato#52]
I don't know if i'm reading something wrong, but it seems that  heartbeat part of `Worker.prototype.onMsg` function checks for params that are not passed by `Worker.prototype.heartbeat`. lacks `rid` param, and requires clientId that is never used. 

Sending heartbeat:
```javascript
  ...
  this.send([
    MDP.WORKER, MDP.W_HEARTBEAT, '',
    JSON.stringify({
      concurrency: this.conf.concurrency
    })
  ...
```

Heartbeat processing event onMsg requires message to have 5 parameters (and it only has 2)
```javascript
if (msg.length === 5) {
  clientId = msg[2];
  rid = msg[4];
  if (rid && this.reqs[rid]) {
    this.reqs[rid].liveness = HEARTBEAT_LIVENESS;
  }
}
```
It's a bit confusing for me ... there are 2 different "livenesses" one is [this|self].liveness and the other is req.liveness. When checking if reply is active req.liveness is tested but stream is still open because testing is done on this.liveness (which on every message is set to HEARTBEAT_LIVENESS)

```javascript
if (self.liveness <= 0) {
  ...
  self.stop();
  
```

**Comment by prdn** [comment]
**liveness**

* A Worker instance has its own liveness. That indicates the status of the connection with the broker.

* A request, when hits a Worker, has its own liveness. The is interesting because a Client, when it sends an heartbeat, can also specify a ```rid``` to inform the Worker that it is still interested to the request.
This is an optional feature that helps is looong running requests.

**heartbeats**

When the Worker receives an heartbeat and the length is === 5, it means that the heartbeat comes directly from a Client for a specific request.

Is more clear now?

**Comment by prdn** [comment]
ps. what is not working for you? 
Do you have an example?

**Comment by kubi** [comment]
I'll try to prepare something over the weekend to show you my problem. In my opinion the internal method `heartbeat` doesn't work. I do a lot of `write()` and every time it "ticks" liveness goes down by 1, and after 3-4 times method `reply.active()` returns false while stream is still up and running

**Comment by prdn** [comment]
It's normal that reply.active gives you `false` because it doesn't receive a specific heartbeat for the related rid.
Indeed it's not well explained... sorry about that.

**Comment by prdn** [comment]
To have reply.active returning `true` the related Client should send heartbeats for that specific Request to notify that the interest in the reply is still alive. This is something very unusual anyway, so we may want to improve this.
Ideas are appreciated

**Comment by kubi** [comment]
Thx for your asnwers. I've solved my problem with stream version of client - all i had to do was:
```javascript
var heartbeat = true,
  pigatoCllient = new pigato.Client();

var stream = pigatoCllient.request('workerName', data)
      .on('data', function(partialData) {} // handle partial data
      .on('end', function() { heartbeat = false; })
      .on('error', function(err) { heartbeat = false; });

// send proper heartbeat;
setInterval(function() {
  stream.heartbeat(); // add heartbeat === true check and clearInterval
},.pigatoClient.conf.heartbeat);
```
