### ISSUE TITLE
When Directory start, it doesn't get automatically the $dir

### ISSUE THREAD

**Issue by maxired** [prdn/pigato#53]
Hi,

when starting a new service.Directory, it is not automatically updated with the good information.

This will be done only after a worker connect or disconnect.

Because Directory is also a worker, once it's connected to the broker, the broker [notify $dir](https://github.com/prdn/pigato/blob/116aaa4597cdd94c131b991051100946533fc832/lib/Broker.js#L585).
Still, the Directory won't get the information because the [intch connection is done afterward.](https://github.com/prdn/pigato/blob/116aaa4597cdd94c131b991051100946533fc832/services/Base.js#L14L17)

**Comment by prdn** [comment]
Hey @maxired 
This should fix: 01a5932fdc7347ae8248f29648075b48d0307eed
Can you confirm that works for you?

**Comment by maxired** [comment]
Thansk @prdn, yes it does solve this issue.

I'm glad you took care of this one ;)
