### ISSUE TITLE
Worker concurrency setting

### ISSUE THREAD

**Issue by kubi** [prdn/pigato#55]
Hi,

I've noticed that even though i set concurrency to 1 on worker creation:
```javascript
var worker = new pigato.Worker('127.0.0.1:5555', 'testName', {concurrency: 1});
```

When i send 10 requests at once they all get handled simultaneously. I did a little research on broker code and it does something like this:

```javascript
_.each(['concurrency'], function(fld) {
      if (!_.isUndefined(opts[fld])) {
        worker.[fld] = opts[fld];
      }
    });
```
it assignes worker.concurrency a value from worker config, but it is never used. `Border.workerAvailable` method checks only worker.opts.concurrency.
```javascript
if (worker.opts.concurrency === -1) {
    return true;
  }

  if (worker.rids.length < worker.opts.concurrency) {
    return true;
  }
```
When i change `worker.[fld] = opts[fld];` to `worker.opts[fld] = opts[fld];` things look a lot better and request handling works like i imagine it would :)

**Comment by prdn** [comment]
Thanks @kubi 
519952c71acf4ec65d1606b9eb7d54b18ddd9048 should fix the issue
