### ISSUE TITLE
socket.identity must be unique for each fresh socket

### ISSUE THREAD

**Issue by allain** [prdn/pigato#60]
When a Worker is stopped and restarted its socket it closed and then a new one is created.

Both sockets share the same identity (the worker name). This causes the second socket to silently drop any messages it sends out.

I was able to resolve this by setting the identity of the created socket to this.conf.name + Date.now(). The sockets don't interfere with each other any more, but then a whole bunch of unit tests start failing since the identity of the socket is used to identify the Worker.

**Comment by allain** [comment]
As an alternative, I have some code that shows you can keep the socket around and just disconnect and reconnect it, but the tests for z9 stuff errors out with "Error: Too many open files". Makes me thing Worker should have a destroy methods which actually relinquishes is resources and leave it in an unusable state (not restartable).

**Comment by prdn** [comment]
@allain I will change the name to a prefix so we can always start from a "fresh" socket identifier, but let the $dir service's clients take advantage of worker recognition from a name/pattern.

Ok for you?

**Comment by prdn** [comment]
Take a look here https://github.com/prdn/pigato/commit/9ebd3f291d3d4c5e157ad46e3e91076217144a2d

**Comment by prdn** [comment]
Fixed
